# Generated by Django 4.2 on 2025-06-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0002_rename_created_at_addon_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-03T12:22:43.183915+05:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
