# Generated by Django 4.2 on 2025-06-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name="User's address"),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="User's city"),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Account creation time'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name="User's current latitude"),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name="User's current longitude"),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="User's postal code"),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profile picture URL'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="User's state"),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last update time'),
        ),
    ]
