# Generated by Django 4.2 on 2025-06-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_applicationuser_address_applicationuser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicationuser',
            name='updated_at',
        ),
    ]
