# Generated by Django 4.2 on 2025-06-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_remove_applicationuser_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationuser',
            name='profile_image',
        ),
    ]
