# Generated by Django 4.2 on 2025-06-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_remove_applicationuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationuser',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='applicationuser',
            name='location_longitude',
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='user_type',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('producer', 'Producer'), ('outlet_manager', 'Outlet Manager'), ('staff', 'Staff')], default='consumer', max_length=20),
        ),
    ]
